version: '3'

networks:
  network-net:
    driver: bridge

services:
  zookeeper-server:
    image: 'bitnami/zookeeper:latest'
    networks:
      - network-net
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka-server:
    image: 'bitnami/kafka:latest'
    networks:
      - network-net    
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-server:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - ALLOW_PLAINTEXT_LISTENER=yes

    depends_on:
      - zookeeper-server
  mongo:
    image: mongo
    networks:
      - network-net
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: MongoDB2021!
    ports:
      - "27017:27017"
  oracle:
    image: store/oracle/database-enterprise:12.2.0.1-slim
    networks:
      - network-net
    ports:
      - 1521:1521
  redis:
    image: redis
    networks:
      - network-net
    ports:
      - 6379:6379
